name: streaming-zarr
channels:
  - conda-forge
dependencies:
  - nodejs
  - bokeh
  - dask
  - matplotlib
  - redis
  - redis-py
  - xarray
  - zarr
  - pip
  - pip:
    - jupyter_bokeh
    - jupyterlab_widgets
